/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MedicalEquipmentEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.EquipmentHandlingOrganization;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicalEquipmentWorkRequest;
import Business.WorkQueue.OperationsWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.MedicalEquipmentWareHouse.MedicalEquipmentWorkArea;

/**
 *
 * @author family
 */
public class MedicalEquipmentManagment extends javax.swing.JPanel {

    /**
     * Creates new form MedicalEquipmentManagment
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private MedicalEquipmentEnterprise medenterprise;
    private Network network;
    private EcoSystem system;
    private Enterprise.EnterpriseType enterpriseType;
    private EquipmentHandlingOrganization equiporg;

    public MedicalEquipmentManagment(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        populateTable();

    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) reuqestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            //for(WorkRequest request : equiporg.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[9];

            row[0] = ((MedicalEquipmentWorkRequest) request);
            String urgencyLevel = ((MedicalEquipmentWorkRequest) request).getUrgencyLevel();
            row[1] = urgencyLevel;
            int quantity = ((MedicalEquipmentWorkRequest) request).getQuantity();
            row[2] = quantity;
            row[3] = request.getSender();
            row[4] = ((MedicalEquipmentWorkRequest) request).getReceiver();
            row[5] = request.getStatus();
            String expectedArrivalTime = ((MedicalEquipmentWorkRequest) request).getExpectedArivalTime();
            row[6] = request.getRequestDate();
            row[7] = ((MedicalEquipmentWorkRequest) request).getActualprice();
            row[8] = ((MedicalEquipmentWorkRequest) request).getLoanedprice();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        equipmentName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        reuqestJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        urgencyLevel = new javax.swing.JComboBox<>();
        sendrequestBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quatityTxtFld = new javax.swing.JSpinner();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(2000, 1200));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("REQUEST MEDICAL EQUIPMENT ");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MEDICAL EQUIPMENT: ");

        equipmentName.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 24)); // NOI18N
        equipmentName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "Stethescope", "Thermometer", "Syringe", "Stretcher", "Blood pressure Kit", "Microscope" }));
        equipmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentNameActionPerformed(evt);
            }
        });

        reuqestJTable.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        reuqestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICAL EQUIPMENT", "MESSAGE", "QUANTITY", "SENDER", "RECIEVER", "STATUS", "REQUEST DATE", "ACTUAL PRICE", "LOAN PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reuqestJTable);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("URGENCY LEVEL:");

        urgencyLevel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        urgencyLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "CRITICAL(<3 HRS)", "MODERATE(<6 HRS)", "LOW(12 HRS)" }));
        urgencyLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgencyLevelActionPerformed(evt);
            }
        });

        sendrequestBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        sendrequestBtn.setText("SEND REQUEST");
        sendrequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrequestBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("QUANTITY:");

        quatityTxtFld.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(196, 196, 196)
                        .addComponent(sendrequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urgencyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quatityTxtFld))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urgencyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quatityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(sendrequestBtn))
                .addContainerGap(547, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendrequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrequestBtnActionPerformed
        // TODO add your handling code here:
        // OperationsWorkRequest request = new OperationsWorkRequest();
        MedicalEquipmentWorkRequest request = new MedicalEquipmentWorkRequest();
        request.setEquipmentName(equipmentName.getSelectedItem().toString());
        request.setSender(account);
        request.setStatus("Sent");
        request.setUrgencyLevel(urgencyLevel.getSelectedItem().toString());
        request.setHospitalName(enterprise.getName());
        request.setQuantity(Integer.parseInt(quatityTxtFld.getValue().toString()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        request.setRequestDate(dateFormat.format(date));
        Random rand = new Random();
        int min = 20;
        int max = 40;
        int n1 = rand.nextInt((max - min)) + 1;
        request.setActualprice(n1);

        int n2 = rand.nextInt(10) + 1;
        request.setLoanedprice(n2);

        Organization org = null;
        //Enterprise.EnterpriseType type=null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                org = organization;
                System.out.println("****" + org);
                break;
            }
        }
        // if (org!=null){

        org.getWorkQueue().getWorkRequestList().add(request);
        account.getWorkQueue().getWorkRequestList().add(request);
        // equiporg.getWorkQueue().getWorkRequestList().add(request);
        System.out.println("****** " + organization.getName());
        System.out.println("******" + enterprise.getName());
        System.out.println("**** " + network.getName());
        for (Network network : system.getNetworkList()) {

            if (network.getName().equals(this.network.getName())) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    System.out.println("****" + enterprise.getName());
                    System.out.println("******" + enterprise.getEnterpriseType());
                    //if(enterprise.getEnterpriseType().equals("MedicalEquipmentWareHouse")){
                    //  Enterprise.EnterpriseType type=null;
                    //if(enterprise.getEnterpriseType().equals("MedicalEquipmentWareHouse")){
                    //if (type==Enterprise.EnterpriseType.MedicalEquipmentWareHouse) { 
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        System.out.println("***** Organizatio Name:" + organization.getName());
                        if (organization.getName().equals("Equipment Organization")) {
                            System.out.println("True");
                            // for( Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()){
                            System.out.println("***** organization Name" + organization.getName());
                            // if(organization.getName().equals("EquipmentOrganization")){
                            organization.getWorkQueue().getWorkRequestList().add(request);
                        }
                    }
                }

            }
            // }

            //  org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);

            populateTable();
        }

    }//GEN-LAST:event_sendrequestBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void urgencyLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgencyLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgencyLevelActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void equipmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> equipmentName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner quatityTxtFld;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable reuqestJTable;
    private javax.swing.JButton sendrequestBtn;
    private javax.swing.JComboBox<String> urgencyLevel;
    // End of variables declaration//GEN-END:variables
}
